name: build
on:
  push:
    branches:
      - main
  pull_request:
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: brew install ninja
      - run: tools/build.sh
      - run: echo asset=$(echo *.tar.*) >> $GITHUB_ENV
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.asset }}
          path: ${{ env.asset }}
  tag_check:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ env.version }}
      should_release: ${{ env.should_release }}
    steps:
      - uses: actions/checkout@v2
      - run: echo version=$(tools/version.sh) >> $GITHUB_ENV
      - run: |
          git fetch --prune --unshallow --tags

          if [ ${{ github.ref }} = 'refs/heads/main' ] && ! git tag | grep v$version; then
            echo should_release=true >> $GITHUB_ENV
          fi
  release:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: artifacts
      - uses: softprops/action-gh-release@v1
        if: needs.tag_check.outputs.should_release == 'true'
        with:
          tag_name: v${{ needs.tag_check.outputs.version }}
          files: artifacts/**
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
