name: build
on:
  push:
    branches:
      - main
  pull_request:
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-20.04
          - macos-12
          - macos-11
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: brew install doxygen ninja
      - run: tools/build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: "*.tar.*"
          if-no-files-found: error
  tag_check:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ env.tag }}
      should_release: ${{ env.should_release }}
    steps:
      - uses: actions/checkout@v2
      - run: echo tag=$(tools/tag.sh) >> $GITHUB_ENV
      - run: |
          git fetch --prune --unshallow --tags

          if [ ${{ github.ref }} = refs/heads/main ] && ! git tag | grep v$tag; then
            echo should_release=true >> $GITHUB_ENV
          fi
  release:
    needs:
      - build
      - tag_check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          path: artifacts
      - uses: softprops/action-gh-release@v1
        if: needs.tag_check.outputs.should_release == 'true'
        with:
          tag_name: v${{ needs.tag_check.outputs.tag }}
          files: artifacts/**
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
